### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Meryalvhe--SimpleCounter#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Buen trabajo @Meryalvhe . Felicitaciones 😸
## Estilo de código y limpieza
- ¡Muy buen trabajo con tu código!
## Mejores prácticas/comentarios
- Recuerda cambiar el `<title>` de tu `index.html`
- Te invito a que añadas un botón de parada y otro de reinicio 
![Captura de pantalla de 2024-04-19 11-16-58](https://github.com/4GeeksAcademy/Meryalvhe--SimpleCounter/assets/139759297/02baed2c-0136-45ca-889b-dfeb67e934ca)

**Comment by Meryalvhe** [comment]
Gracias Edo, 
Lo tendré en cuenta para ponerlo en practica!
